test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... ERROR
test_grades (__main__.TestExercice) ... FAIL
test_histogram (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_doubles (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 49, in test_doubles
    output = [exercice.contains_doubles(v) for v in values]
  File "test_exercice.py", line 49, in <listcomp>
    output = [exercice.contains_doubles(v) for v in values]
  File "/home/runner/work/c03_ch6_exercices-MatthewRajala/c03_ch6_exercices-MatthewRajala/exercice.py", line 40, in contains_doubles
    return (len(list) == len(set(list)))
TypeError: object of type 'type' has no len()

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_anagram
    'Erreur dans la vérification de l\'anagramme'
AssertionError: Lists differ: [None, None] != [True, False]

First differing element 0:
None
True

- [None, None]
+ [True, False] : Erreur dans la vérification de l'anagramme

======================================================================
FAIL: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 69, in test_grades
    'Erreur dans les notes'
AssertionError: [{}] is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: test_histogram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 84, in test_histogram
    'Erreur dans les histogrammes'
AssertionError: [({}, []), ({}, [])] is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_order
    'Mauvais ordre'
AssertionError: Lists differ: [True, True] != [[-2, 1, 6, 9], ['2', 'a', 'hello']]

First differing element 0:
True
[-2, 1, 6, 9]

- [True, True]
+ [[-2, 1, 6, 9], ['2', 'a', 'hello']] : Mauvais ordre

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4, errors=1)
